/**
 * Do not edit directly
 * Generated on Tue, 28 Jun 2022 21:05:13 GMT
 */

export const color_brand_primary = "#0967d2"; // Our beloved CoCam deep blue. Use only for branding purposes.
export const color_brand_secondary = "#142334"; // Complements our primary blue. Use only for branding purposes.
export const color_brand_accent = "#ffd000"; // Used to indicate something is new or coming soon. When used as a background color, pair with color_text_secondary.
export const color_brand_upgrade = "#0ce8d6"; // Used to indicate something is part of the Pro plan or part of an upgrade path. When used as a background color, pair with color_text_secondary.
export const color_background_1_le = "#ffffff"; // The default background color in light environments.
export const color_background_1_de = "#142334";
export const color_background_2_le = "#f5f7fa"; // Use to highlight supporting content: sidebars, modal footers, callouts, etc. Do not use for button backgrounds.
export const color_background_2_de = "#192d43";
export const color_background_3_le = "#ebeff5"; // Use when level 2 is too light: chip and avatar backgrounds, for example. Do not use for button backgrounds.
export const color_background_3_de = "#1f3751";
export const color_text_default_le = "#142334"; // Body copy font color in our apps.
export const color_text_default_de = "#ffffff";
export const color_text_subtle_le = "#4d5a68"; // Use for supporting content: helper text, metadata, etc.
export const color_text_subtle_de = "#c3c8cc";
export const color_text_nonessential_le = "#8191a2"; // Our lightest font color. Use sparingly in hint text, input placeholder text, etc.
export const color_text_nonessential_de = "#a0a7af";
export const color_button_background_primary_le = "#0967d2"; // Background or outline border color for our primary solid/outline buttons.
export const color_button_background_primary_de = "#6fabf1";
export const color_button_background_secondary_le = "#142334"; // Background or outline border color for our secondary solid/outline buttons.
export const color_button_background_secondary_de = "#ffffff";
export const color_button_background_subtle_le = "#ebeff5"; // Background or border color for subtle buttons in light env.
export const color_button_background_subtle_de = "#2a415a"; // Background or border color for subtle buttons in dark env.
export const color_button_background_tint_le = "#e5f1ff"; // Light background color tint for hover and active button states
export const color_button_background_tint_de = "rgba(255, 255, 255, 0.1)";
export const color_button_text_primary_le = "#ffffff"; // Text color for our primary solid buttons.
export const color_button_text_primary_de = "#142334";
export const color_button_text_secondary_le = "#ffffff"; // Text color for our secondary solid buttons.
export const color_button_text_secondary_de = "#142334";
export const color_button_text_subtle_le = "#4d5a68"; // Text color for our subtle solid buttons.
export const color_button_text_subtle_de = "#c3c8cc";
export const color_link_primary_le = "#0967d2"; // Text color for primary links, as well as our minimal or outline buttons.
export const color_link_primary_de = "#6fabf1";
export const color_link_secondary_le = "#142334"; // Text color for secondary links, as well as our minimal or outline buttons.
export const color_link_secondary_de = "#ffffff";
export const color_link_subtle_le = "#4d5a68"; // Text color for subtle links, as well as our minimal or outline buttons.
export const color_link_subtle_de = "#c3c8cc";
export const color_border_default_le = "rgba(20, 35, 52, 0.12)"; // Our default border color, designed to separate content. Do not use for button or input borders.
export const color_border_default_de = "rgba(255, 255, 255, 0.15)";
export const color_border_input_inactive_le = "rgba(20, 35, 52, 0.2)"; // Border color for form inputs in their inactive state.
export const color_border_input_inactive_de = "rgba(255, 255, 255, 0.22)";
export const color_border_input_active_le = "#0967d2"; // Border color for form inputs in their active state.
export const color_border_input_active_de = "#6fabf1";
export const color_utility_destroy = "#ef4e4e"; // Use to warn the user of destructive actions or app errors.
export const color_utility_caution = "#ffd000"; // Use to call attention to important information or warnings.
export const color_utility_success = "#3ebd93"; // Use to confirm a successfully completed action.
export const color_utility_info_le = "#4d5a68"; // Use to inform the user about a neutral state or action.
export const color_utility_info_de = "#4d5a68";
export const color_depth_1_le = "rgba(20, 35, 52, 0.13)"; // Color for lowest-elevation shadows. Use for tooltips.
export const color_depth_1_de = "rgba(6, 10, 16, 0.5)";
export const color_depth_2_le = "rgba(20, 35, 52, 0.13)"; // Color for mid-elevation shadows. Use for cards and popovers.
export const color_depth_2_de = "rgba(6, 10, 16, 0.6)";
export const color_depth_3_le = "rgba(20, 35, 52, 0.2)"; // Color for highest-elevation shadows. Use for modals, floating action bars, etc.
export const color_depth_3_de = "rgba(6, 10, 16, 0.7)";
export const color_label_green = "#31a03c";
export const color_label_blue = "#4191ed";
export const color_label_purple = "#a227c5";
export const color_label_navy = "#354b62";
export const color_label_yellow = "#ffd000";
export const color_label_orange = "#e76119";
export const color_label_red = "#c73732";
export const color_label_light_gray = "#828c95";
export const color_label_dark_gray = "#4d5a68";
export const color_collab_purple = "#a227c5";
export const color_collab_orange = "#e76119";
export const color_collab_green = "#31a03c";
export const color_collab_blue = "#4191ed";
export const color_collab_red = "#c73732";
export const color_collab_yellow = "#d28e09";
export const color_collab_navy = "#354b62";
export const color_collab_plum = "#413ecf";
export const color_collab_magenta = "#d63baa";
export const color_collab_brown = "#745138";
export const color_collab_owner = "#ffd000";
export const size_spacing_xxs = 2;
export const size_spacing_xs = 4;
export const size_spacing_s = 8;
export const size_spacing_m = 16;
export const size_spacing_l = 24;
export const size_spacing_xl = 32;
export const size_spacing_xxl = 48;
export const size_border_width_s = 1; // Our lightest border width. Use with our default border color to separate content.
export const size_border_width_m = 2; // Light border width for slightly more emphasis than `s`. Use for focus outline states, outline buttons, etc.
export const size_border_width_l = 4; // Mid-thickness border width. Use for tab-highlight bottom border, for example.
export const size_border_width_xl = 8; // Our heaviest border width. Use for accent-color side border width in Toasts, for example.
export const size_border_radius_s = 2; // Gives sharp corners a very slight rounding. Use sparingly and only on small elements like `tiny`-sized components.
export const size_border_radius_m = 4; // Our default border radius for buttons on mobile and labels on both platforms.
export const size_border_radius_l = 8; // Our default border radius for buttons and modals on the web.
export const size_border_radius_xl = 16; // Currently unused.
export const size_border_radius_xxl = 24; // Our default border radius for modals on mobile.
export const size_border_radius_pill = 1000; // Use to create pill-shaped UI elements like chips.
export const size_text_xxs = 10; // Use sparingly when space is at a minimum - preferably only on mobile.
export const size_text_xs = 12; // Use for metadata (date published, etc.) on mobile and on the web where space is tight.
export const size_text_s = 14; // Our default font size on mobile. Can also be used as body copy and metadata on the web.
export const size_text_m = 16; // Our default font size on the web.
export const size_text_l = 20; // Use for headings or featured copy.
export const size_text_xl = 24; // Use for headings.
export const size_text_xxl = 32; // Use for headings.
export const size_text_xxxl = 42; // Use for headings.
export const size_avatar_xs = 16;
export const size_avatar_s = 24;
export const size_avatar_m = 32;
export const size_avatar_l = 40;
export const size_depth_1_blur = 3; // Blur value in pixels for lowest-elevation shadow. Use for tooltips.
export const size_depth_1_y = 1; // Y offset value in pixels for lowest-elevation shadow. Use for tooltips.
export const size_depth_2_blur = 6; // Blur value in pixels for medium-elevation shadow. Use for cards and popovers.
export const size_depth_2_y = 2; // Y offset value in pixels for medium-elevation shadow. Use for cards and popovers.
export const size_depth_3_blur = 12; // Blur value in pixels for highest-elevation shadow. Use for modals, floating action bars, etc.
export const size_depth_3_y = 4; // Y offset value in pixels for highest-elevation shadow. Use for modals, floating action bars, etc.
